import ProjectDescription
import ProjectDescriptionHelpers

// MARK: - Project

let project = Project(
  name: "ArchiveUIComponents",
  organizationName: Project.organizationName,
  packages: [],
  targets: Project.dynamicFrameworkTargets(
    name: "ArchiveUIComponents",
    destinations: .iOS,
    frameworkDependencies: [
      .project(
        target: "ArchiveFoundation",
        path: "../ArchiveFoundation"
      )
    ],
    testDependencies: [],
    targetScripts: [
      .pre(script: "${PROJECT_DIR}/../../Tools/LocalizationGen/LocalizationGen.sh", name: "LocalizationAutoGen"),
      .pre(script: "${PROJECT_DIR}/../../Tools/swiftgen config run --config \"${PROJECT_DIR}/../App/Resources/uiComponentsSwiftgen.yml\"", name: "Gen"),
      .pre(script: "${PROJECT_DIR}/../../Tools/swiftlint --config \"${PROJECT_DIR}/../App/Resources/swiftlint.yml\"", name: "Lint")
    ],
    coreDataModel: [],
    resources: ["${PROJECT_DIR}/../../App/Resources/**"],
    additionalSourcePaths: [
      "${PROJECT_DIR}/../../App/Sources/1.Extension/DesignFont.swift",
      "${PROJECT_DIR}/../../App/Sources/1.AutoGenerated/LocalizableMap.swift",
    ]
  ),
  schemes: [],
  additionalFiles: [],
  resourceSynthesizers: [
    .assets()
  ]
)
