//
//  NotificationDefine.swift
//  App
//
//  Created by Hanwe LEE on 2024/01/21.
//

final class NotificationDefine {
  static let USER_LOGGED_IN_NOTIFICATION_DEFINE = "USER_LOGGED_IN_NOTIFICATION_DEFINE"
  static let USER_LOGGED_OUT_NOTIFICATION_DEFINE = "USER_LOGGED_OUT_NOTIFICATION_DEFINE"
  static let APP_DID_BECOME_ACTIVE_NOTIFICATION_DEFINE = "APP_DID_BECOME_ACTIVE_NOTIFICATION_DEFINE"
  static let APP_WILL_RESIGN_ACTIVE_NOTIFICATION_DEFINE = "APP_WILL_RESIGN_ACTIVE_NOTIFICATION_DEFINE"
  static let APP_WILL_ENTER_FOREGROUND_NOTIFICATION_DEFINE = "APP_WILL_ENTER_FOREGROUND_NOTIFICATION_DEFINE"
  static let APP_DID_ENTER_BACKGROUND_NOTIFICATION_DEFINE = "APP_DID_ENTER_BACKGROUND_NOTIFICATION_DEFINE"
}
