//
//  NotificationDefine.swift
//  ArchiveFoundation
//
//  Created by hanwe on 6/22/24.
//  Copyright © 2024 TeamArchive. All rights reserved.
//

public final class NotificationDefine {
  public static let USER_LOGGED_IN_NOTIFICATION_DEFINE = "USER_LOGGED_IN_NOTIFICATION_DEFINE"
  public static let USER_LOGGED_OUT_NOTIFICATION_DEFINE = "USER_LOGGED_OUT_NOTIFICATION_DEFINE"
  public static let APP_DID_BECOME_ACTIVE_NOTIFICATION_DEFINE = "APP_DID_BECOME_ACTIVE_NOTIFICATION_DEFINE"
  public static let APP_WILL_RESIGN_ACTIVE_NOTIFICATION_DEFINE = "APP_WILL_RESIGN_ACTIVE_NOTIFICATION_DEFINE"
  public static let APP_WILL_ENTER_FOREGROUND_NOTIFICATION_DEFINE = "APP_WILL_ENTER_FOREGROUND_NOTIFICATION_DEFINE"
  public static let APP_DID_ENTER_BACKGROUND_NOTIFICATION_DEFINE = "APP_DID_ENTER_BACKGROUND_NOTIFICATION_DEFINE"
}
